project_id = "qdqmhgwjupsoradhktzu"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
ip_version = "ipv4"

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54329
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_sms_confirmations = false

[functions]
enabled = true

[functions.ai-job-search]
verify_jwt = false

[functions.ai-navigate]
verify_jwt = false

[functions.api-gateway]
verify_jwt = false

[functions.search-agencies]
verify_jwt = true

[functions.process-agency-pdf]
verify_jwt = true

[functions.translate-content]
verify_jwt = false

[functions.bulk-translate-content]
verify_jwt = false

[functions.process-translation-queue]
verify_jwt = false