-- Add logos to organizations from SEQ Programs document
UPDATE public.resources SET logo_url = '/resource-logos/scope-education-services-logo.png', updated_at = now() WHERE organization_name = 'Scope Education Services';
UPDATE public.resources SET logo_url = '/resource-logos/new-deal-after-school-logo.jpg', updated_at = now() WHERE organization_name = 'New Deal After School ';
UPDATE public.resources SET logo_url = '/resource-logos/queens-public-library-logo.png', updated_at = now() WHERE organization_name = 'Queens Public Library - Cambria Heights';
UPDATE public.resources SET logo_url = '/resource-logos/queens-public-library-logo.png', updated_at = now() WHERE organization_name = 'Queens Public Library - South Hollis';
UPDATE public.resources SET logo_url = '/resource-logos/queens-public-library-logo.png', updated_at = now() WHERE organization_name = 'Queens Public Library - St. Albans';
UPDATE public.resources SET logo_url = '/resource-logos/joes-academy-of-music-logo.jpg', updated_at = now() WHERE organization_name = 'Joe''s Academy of Music';
UPDATE public.resources SET logo_url = '/resource-logos/my-first-school-experience-logo.png', updated_at = now() WHERE organization_name = 'My First School Experience';
UPDATE public.resources SET logo_url = '/resource-logos/cookerz-blend-logo.png', updated_at = now() WHERE organization_name = 'Cookerz Blend';
UPDATE public.resources SET logo_url = '/resource-logos/cove-restaurant-logo.png', updated_at = now() WHERE organization_name = 'Cove Restaurant';
UPDATE public.resources SET logo_url = '/resource-logos/hibiscus-restaurant-logo.jpg', updated_at = now() WHERE organization_name = 'Hibiscus Restaurant';
UPDATE public.resources SET logo_url = '/resource-logos/cara-mia-logo.jpg', updated_at = now() WHERE organization_name = 'Cara Mia';
UPDATE public.resources SET logo_url = '/resource-logos/blue-seafood-restaurant-logo.png', updated_at = now() WHERE organization_name = 'Blue Seafood Restaurant';
UPDATE public.resources SET logo_url = '/resource-logos/caribbean-soul-logo.png', updated_at = now() WHERE organization_name = 'Caribbean Soul';
UPDATE public.resources SET logo_url = '/resource-logos/the-figure-studio-logo.jpg', updated_at = now() WHERE organization_name = 'The Figure Studio';
UPDATE public.resources SET logo_url = '/resource-logos/eastern-queens-boxing-club-logo.png', updated_at = now() WHERE organization_name = 'Eastern Queens Boxing Club';
UPDATE public.resources SET logo_url = '/resource-logos/eastern-queens-boxing-club-logo.png', updated_at = now() WHERE organization_name = 'Lyfe Boxing';
UPDATE public.resources SET logo_url = '/resource-logos/bella-luna-wellness-logo.jpg', updated_at = now() WHERE organization_name = 'Bella Luna Wellness';
UPDATE public.resources SET logo_url = '/resource-logos/angel-spa-logo.jpg', updated_at = now() WHERE organization_name = 'Angel Spa';
UPDATE public.resources SET logo_url = '/resource-logos/breaking-barriers-logo.png', updated_at = now() WHERE organization_name = 'Breaking Barriers Mental Health Counseling PLLC';
UPDATE public.resources SET logo_url = '/resource-logos/well-life-network-logo.jpg', updated_at = now() WHERE organization_name = 'Well Life Network';
UPDATE public.resources SET logo_url = '/resource-logos/transitional-services-ny-logo.png', updated_at = now() WHERE organization_name = 'Transitional Services for New York (Mieles Respite)';
UPDATE public.resources SET logo_url = '/resource-logos/greater-jamaica-development-logo.jpg', updated_at = now() WHERE organization_name = 'Greater Jamaica Development Corporation';
UPDATE public.resources SET logo_url = '/resource-logos/queens-business-center-logo.png', updated_at = now() WHERE organization_name = 'Queens Business Center';
UPDATE public.resources SET logo_url = '/resource-logos/nyc-small-business-solutions-logo.png', updated_at = now() WHERE organization_name = 'NYC Small Business Solutions';
UPDATE public.resources SET logo_url = '/resource-logos/queens-corporate-center-logo.png', updated_at = now() WHERE organization_name = 'Queens Corporate Center';
UPDATE public.resources SET logo_url = '/resource-logos/queens-community-house-logo.png', updated_at = now() WHERE organization_name = 'Queens Community House - Senior Programs';
UPDATE public.resources SET logo_url = '/resource-logos/alpha-phi-alpha-senior-center-logo.png', updated_at = now() WHERE organization_name = 'Alpha Phi Alpha Senior Center';
UPDATE public.resources SET logo_url = '/resource-logos/snap-brookville-center-logo.jpg', updated_at = now() WHERE organization_name = 'SNAP Brookville Center';
UPDATE public.resources SET logo_url = '/resource-logos/allen-community-senior-citizen-logo.jpg', updated_at = now() WHERE organization_name = 'Allen Community Senior Citizen Centers';
UPDATE public.resources SET logo_url = '/resource-logos/centerlight-healthcare-logo.png', updated_at = now() WHERE organization_name = 'Centerlight Healthcare';
UPDATE public.resources SET logo_url = '/resource-logos/golden-years-senior-programs-logo.png', updated_at = now() WHERE organization_name = 'Golden Years Senior Programs';
UPDATE public.resources SET logo_url = '/resource-logos/floral-park-bellerose-senior-logo.jpg', updated_at = now() WHERE organization_name = 'Floral Park-Bellerose Senior Citizens';
UPDATE public.resources SET logo_url = '/resource-logos/life-camp-logo-new.png', updated_at = now() WHERE organization_name = 'Life Camp';
UPDATE public.resources SET logo_url = '/resource-logos/united-methodist-church-logo.png', updated_at = now() WHERE organization_name = 'United Methodist Church of Floral Park';
UPDATE public.resources SET logo_url = '/resource-logos/ymca-greater-ny-logo.png', updated_at = now() WHERE organization_name = 'YMCA of Greater New York - Jamaica';
UPDATE public.resources SET logo_url = '/resource-logos/jamaica-family-wellness-center-logo.jpg', updated_at = now() WHERE organization_name = 'Jamaica Family Wellness Center';
UPDATE public.resources SET logo_url = '/resource-logos/floral-park-public-library-logo.png', updated_at = now() WHERE organization_name = 'Floral Park Public Library';
UPDATE public.resources SET logo_url = '/resource-logos/masjid-eesa-ibn-maryam-logo.png', updated_at = now() WHERE organization_name = 'Masjid Eesa ibn Maryam';
UPDATE public.resources SET logo_url = '/resource-logos/resort-world-career-center-logo.png', updated_at = now() WHERE organization_name = 'Resort World Career Center';
UPDATE public.resources SET logo_url = '/resource-logos/hollis-avenue-senior-buddy-logo.jpg', updated_at = now() WHERE organization_name = 'Hollis Avenue Senior Buddy System';
UPDATE public.resources SET logo_url = '/resource-logos/golden-dancerettes-logo.png', updated_at = now() WHERE organization_name = 'Golden Dancerettes';