-- Add new community resources from PDF

-- Sports Organizations
INSERT INTO resources (organization_name, description, categories, phone, email, address, website, logo_url, type)
VALUES
  ('United Black Golfers Association', 
   'The United Black Golfers Association, Inc. is a Laurelton Queens-based Association, that was formed on March 3, 2014, as a 501(C)(3) not-for-profit corporation. The purpose of the association is to provide opportunities for golfers and individuals of all genders who are interested in the game of golf, to meet and engage in activities that promote unity, and for personal growth and enrichment through the sport of golf. From 2016-2024 UBGA has distributed 68 scholarships to High School Seniors, with a total disbursement of $52,600.00.',
   ARRAY['sports']::text[],
   '(917) 300-8310',
   NULL,
   'PO Box 110417, Cambria Heights, NY 11411',
   'https://ubga.org/',
   '/resource-logos/united-black-golfers-logo.png',
   'resource'),
   
  ('New York Surf School',
   'A Surf school for those interested in learning how to surf in New York.',
   ARRAY['sports']::text[],
   '(718) 916-5359',
   'nysurfschool@gmail.com',
   'Beach 69th St and Beach Front Rd, Arverne, NY 11692',
   'https://newyorksurfschool.com',
   '/resource-logos/ny-surf-school-logo.png',
   'resource'),
   
  ('Queens Alliance Baseball League',
   'The Queens Alliance Baseball League is Queens longest running and established 18 & over adult league. Featuring 20+ teams, this Sunday double-header league offers the perfect level of baseball for every player.',
   ARRAY['sports']::text[],
   '(718) 366-7717',
   'QABL@live.com',
   'Springfield Gardens, NY 11413',
   'https://queensalliancebaseball.com',
   NULL,
   'resource'),
   
  ('Queens United Cricket Academy',
   'Queens United Cricket Academy is New York''s premier cricket training academy, established to teach youngsters the skills of the game and to inspire them with its foundations - team work, honesty, integrity and fair play. Our vision is to create a center of excellence for young talented cricketers who want to take their game to the highest level. All our programs are run by coaches certified from ICC accredited training programs. We welcome boys and girls of all ages and ability.',
   ARRAY['sports', 'educational']::text[],
   '(917) 805-5290',
   NULL,
   '14717-14899 223rd St, Springfield Gardens, NY 11413',
   'https://quca.org',
   '/resource-logos/queens-united-cricket-logo.jpg',
   'resource'),
   
  ('IS8 Nike Basketball',
   'Youth basketball program providing competitive and recreational opportunities.',
   ARRAY['sports']::text[],
   NULL,
   NULL,
   NULL,
   'https://basketball.exposureevents.com/organizations/31909/is8-nike-basketball',
   NULL,
   'resource'),
   
  ('Police Athletic League PAL NYC',
   'The Police Athletic League (or PAL) is New York City''s largest independent youth development not-for-profit organization. We operate diverse programs from Head Start, Day Care and Universal Pre-K programs; to elementary and middle school after-school programs; and summer day camps and summer Playstreets. We run evening teen centers; and college readiness programs, as well as youth employment, juvenile justice programs. Competitive and recreational sports for children of all ages is a cornerstone of our youth development strategy.',
   ARRAY['sports', 'recreational', 'educational']::text[],
   '(718) 454-4957 ext. 2',
   'rcoleman@palnyc.org',
   '109-89 204 Street corner of Hollis Avenue, St Albans, NY 11412',
   'https://palnyc.org/',
   '/resource-logos/police-athletic-league-logo.png',
   'resource'),

-- Community/Recreational Organizations
  ('National Council of Negro Women (NCNW) Queens County',
   'On May 13, 1987, Reva M. Anthony organized and formed the NCNW Inc., Queens County Section based on a growing need for community based program services in Southeast Queens. The Section members established 11 program committees focused on the areas of health, education, cultural arts, voters education, good & welfare, big sisters, community service, social welfare, religion, membership and economic development.',
   ARRAY['recreational']::text[],
   NULL,
   'ncnwqueens@gmail.com',
   'P.O. Box 340105, Jamaica, New York 11434',
   'https://ncnwqueenscounty.org/',
   '/resource-logos/ncnw-queens-logo.jpg',
   'resource'),
   
  ('Jack and Jill of America, Inc. - Queens Chapter',
   'Founded in June 1952, the Queens (New York) Chapter of Jack and Jill of America, Inc. was established under the guidance of Emilie Pickens, who also had the distinction of being the first Vice President of the national organization. We are an organization of over 50 mothers whose objective is to impart constructive educational, civic, cultural, recreational, and social programming to stimulate growth and development in our African-American children. We strive to nurture future leaders through outstanding chapter programming, community service, legislative advocacy, and philanthropic giving.',
   ARRAY['recreational', 'educational']::text[],
   NULL,
   NULL,
   'Cambria Heights, NY 11411',
   'https://jackandjillinc.org',
   '/resource-logos/jack-and-jill-queens-logo.png',
   'resource'),
   
  ('Greater Queens NY Chapter of the Links, Inc.',
   'Community service organization focused on enriching, sustaining and ensuring the culture and economic survival of African Americans and persons of African descent.',
   ARRAY['recreational']::text[],
   NULL,
   NULL,
   'PO Box 110295, Cambria Heights, New York 11411',
   NULL,
   NULL,
   'resource'),
   
  ('The Kiwanis of the Rockaways',
   'Community service organization dedicated to improving the world one child and one community at a time.',
   ARRAY['recreational']::text[],
   NULL,
   'contact@kiwanisoftherockaways.org',
   NULL,
   'https://kiwanisoftherockaways.org/',
   '/resource-logos/kiwanis-rockaways-logo.png',
   'resource'),
   
  ('Queens East Division Kiwanis Cambria Heights',
   'Local chapter of Kiwanis International, serving children and communities.',
   ARRAY['recreational']::text[],
   '(347) 972-9493',
   NULL,
   '187-26 Linden Blvd, Saint Albans, NY',
   'https://w.kiwanis-ny.org/clubdiva.htm?division=Queens%20East',
   '/resource-logos/kiwanis-ny-district-logo.png',
   'resource'),
   
  ('Rotary Club of South Queens',
   'Rotary brings together a global network of volunteer leaders who dedicate their time and talent to tackle the world''s most pressing humanitarian challenges. Rotary connects 1.2 million members from more than 200 countries and geographical areas. Their work impacts lives at both the local and international levels.',
   ARRAY['recreational']::text[],
   NULL,
   'fmcfifteen@gmail.com',
   'P.O. Box 280743, Queens Village, NY 11428-9997',
   'https://southqueensrotary.org/',
   '/resource-logos/rotary-south-queens-logo.png',
   'resource'),
   
  ('The Queens United Lions Club',
   'Lions have a dynamic history. Founded in 1917, we are best known for fighting blindness, but we also volunteer for many different kinds of community projects - including caring for the environment, feeding the hungry and aiding seniors and the disabled. Lions give sight by conducting vision screenings, equipping hospitals and clinics, distributing medicine and raising awareness of eye disease.',
   ARRAY['recreational']::text[],
   NULL,
   'queensunitedlionsclub@gmail.com',
   '51-11 108th Street, Corona, NY 11368',
   'https://e-clubhouse.org/sites/queens_united/',
   '/resource-logos/queens-united-lions-logo.png',
   'resource'),
   
  ('Boy Scouts Troop 333',
   'The Boy Scouts of America is one of the nation''s largest and most prominent values-based youth development organizations. Since 1910, Scouting has helped mold the future leaders of this country by combining educational activities and lifelong values with fun. Scouting helps youth develop academic skills, self-confidence, ethics, leadership skills, and citizenship skills that influence their adult lives. Programs for Cub Scouts (ages 6-11).',
   ARRAY['recreational', 'educational']::text[],
   '(718) 528-0577',
   'troop333queens@gmail.com',
   '115-58 222 Street, Cambria Heights, NY 11411',
   'https://sacredheartny.org/boy-scouts-troop-333',
   '/resource-logos/boy-scouts-333-logo.png',
   'resource'),
   
  ('HAUP',
   'HAUP is dedicated to empowering and serving the community. HAUP provides a supportive environment through education, training, culture, networking opportunities, and other support services, that allows the community to successfully adapt and thrive.',
   ARRAY['recreational', 'educational']::text[],
   '(718) 527-3776',
   NULL,
   '209-05 Jamaica Ave, Queens Village, NY 11428',
   'https://www.haupinc.org/',
   '/resource-logos/haup-logo.png',
   'resource'),
   
  ('Igbo Organization Inc.',
   'Igbo Organization Inc is a non-profit organization based in Saint Albans, New York that focuses on promoting and preserving Igbo culture through cultural performances, historical activities, and commemorative events. The organization is classified as a charitable organization promoting cultural awareness and community engagement.',
   ARRAY['arts', 'recreational']::text[],
   '(718) 413-2013',
   NULL,
   '190-01 Linden Blvd, Jamaica, NY 11412',
   'http://www.igboorganizationny.org/',
   '/resource-logos/igbo-organization-logo.png',
   'resource')
ON CONFLICT DO NOTHING;