-- Insert Business category resources
INSERT INTO public.resources (organization_name, description, phone, email, address, website, categories, type, logo_url)
VALUES
  ('Blaque Resource Network', 'Space for Black people in Queens NY to connect, share resources, and build community.', NULL, NULL, NULL, NULL, ARRAY['recreational'], 'resource', NULL),
  ('JFK Gateway', 'Provides neighborhood services, improvements and advocacy for the District''s off-airport cargo community.', '(516) 730-3400', NULL, '167-43 148th Ave, Jamaica, NY 11434', NULL, ARRAY['recreational'], 'resource', NULL),
  ('Bellerose BID', 'Business improvement district serving Bellerose Village community.', NULL, 'villageclerk@bellerosevillage.org', '50 Superior Road, Bellerose Village, NY 11001', NULL, ARRAY['recreational'], 'resource', NULL),
  ('Southeast Queens Chamber of Commerce', 'Promotes health, wealth, and community growth through local partnerships, events, and beautification efforts.', '(917) 720-2485', NULL, '115-42 Sutphin Blvd, Jamaica, NY 11434', NULL, ARRAY['recreational'], 'resource', NULL),
  ('Eastern Queens Alliance', 'Unites civic groups to tackle shared community issues in Southeast Queens.', '(347) 824-2301', NULL, '222-02 149th Ave, Springfield Gardens, NY 11413', NULL, ARRAY['recreational'], 'resource', NULL),
  ('Southeast Queens Residential Environmental Justice Coalition', 'Provides active and direct liaison with community residents, city agencies, and community-based organizations.', '(631) 594-9174', 'info@sqrejc.org', NULL, NULL, ARRAY['recreational'], 'resource', NULL),

-- Insert Arts category resources
  ('Afrikan Poetry Theatre', 'Provides cultural and educational programs & workshops in Southeast Queens.', '(718) 523-3312', NULL, '176-03 Jamaica Ave, Jamaica, NY 11432', NULL, ARRAY['arts'], 'resource', NULL),
  ('Glass Dolls & Toy Soldiers Dance Company', 'Provides high-quality, accessible dance education to youth in Southside Jamaica, Queens.', '(917) 273-9386', NULL, NULL, NULL, ARRAY['arts'], 'resource', NULL),
  ('Golden Dancerettes', 'Provides the safest and most up to date dance knowledge in a loving, family-friendly, and nurturing environment.', '(929) 288-3163', NULL, '200-02 Linden Blvd, Saint Albans, NY 11412', NULL, ARRAY['arts'], 'resource', NULL),

-- Insert Recreational category resources
  ('United Black Men of Queens Foundation', 'Individuals who are actively forging a unique and distinct pathway towards achieving lasting success and notable accomplishments in their lives and careers by embracing challenges, seizing opportunities, and continuously pursuing excellence.', NULL, 'info@ubmq.org', '157-11 Rockaway Blvd, Jamaica, NY', NULL, ARRAY['recreational'], 'resource', '/resource-logos/ubmq-logo.jpg'),
  ('Kappa Alpha Psi Queens Alumni', 'Established in 1930, the Northeastern Province of Kappa Alpha Psi Fraternity continues to serve as a fraternal model of operational excellence. Guide Right programming represents our commitment to developing youth into the next generation of professional and community leadership.', NULL, 'QANupes@Gmail.com', 'PO BOX 340412, Jamaica, NY 11434', NULL, ARRAY['recreational'], 'resource', '/resource-logos/kappa-alpha-psi-logo.jpg'),
  ('Omega Psi Phi Queens Alumni', 'Nu Omicron Chapter of Omega Psi Phi Fraternity, serving Queens, NYC since 1947.', '(718) 322-9671', NULL, '123-10 143rd St, Jamaica, NY 11436', NULL, ARRAY['recreational'], 'resource', '/resource-logos/omega-psi-phi-logo.jpg'),
  ('Phi Beta Sigma Queens Alumni', 'Queens & Long Island Alumni chapter of Phi Beta Sigma Fraternity.', '(202) 726-5434', 'adavis@phibetasigma1914.org', 'P.O. Box 120383, St. Albans, NY 11412-0383', NULL, ARRAY['recreational'], 'resource', '/resource-logos/phi-beta-sigma-logo.jpg'),
  ('Alpha Phi Alpha Queens Alumni', 'Zeta Zeta Lambda Chapter has been an exceptional active part of the Saint Albans, Queens community since its inception on April 24, 1955.', NULL, NULL, '220-01 Linden Blvd, Jamaica, NY 11411', NULL, ARRAY['recreational'], 'resource', '/resource-logos/alpha-phi-alpha-logo.jpg'),
  ('Sigma Gamma Rho Queens Alumni', 'Nu Beta Sigma chapter serving Queens community.', NULL, 'info@nubetasigma.org', 'P.O. Box 280651, Queens Village, NY 11428', NULL, ARRAY['recreational'], 'resource', '/resource-logos/sigma-gamma-rho-logo.jpg'),
  ('Delta Sigma Theta Queens Alumni', 'Organization of college-educated women committed to the constructive development of its members and to public service with a primary focus on the Black community.', NULL, 'Membership@dstquac.org', 'P.O. Box 340132, Rochdale Village Station, Jamaica, NY 11434-0132', NULL, ARRAY['recreational'], 'resource', '/resource-logos/delta-sigma-theta-logo.jpg'),
  ('American Legion Post 483', 'Veterans post providing assistance and shelter to veterans who have served this country.', '(347) 676-7133', NULL, '240-08 135th Ave, Rosedale, NY 11422', NULL, ARRAY['recreational'], 'resource', NULL),
  ('Project New Yorker', 'Nonprofit organization dedicated to empowering under-resourced Bangladeshi immigrant women and youth.', '(718) 737-2398', NULL, '169-18 Hillside Avenue (2nd Floor), Jamaica, NY 11432', 'https://projectnewyorker.org/', ARRAY['recreational'], 'resource', NULL),
  ('NAACP Jamaica Branch', 'To achieve equity, political rights, and social inclusion by advancing policies and practices that expand human and civil rights, eliminate discrimination, and accelerate the well-being, education, and economic security of Black people and all persons of color.', '(718) 723-3653', NULL, '89-14 Parsons Blvd Suite 5-40, Jamaica, NY 11432', 'https://naacp.org', ARRAY['recreational'], 'resource', NULL),
  ('A Better Jamaica', 'Engaged in activities designed to strengthen the set of southeast Queens, New York neighborhoods known collectively as Jamaica.', '(718) 657-2605', NULL, '114-73 178th Street, Jamaica, New York 11434', 'https://abetterjamaica.org', ARRAY['recreational'], 'resource', NULL),
  ('Jamaica 311', 'Community reporting platform brought to you by A Better Jamaica.', NULL, NULL, NULL, 'https://jamaica311.com', ARRAY['recreational'], 'resource', NULL),
  ('Showing Hearts Foundation', 'A non-profit organization committed to educating, empowering, and uplifting underserved communities through organizational support, youth economic development, and community outreach.', NULL, 'team@showinghearts.org', NULL, 'https://showinghearts.org', ARRAY['recreational'], 'resource', NULL),
  ('Rising Ground', 'Provides caring support and proven paths to positive change, helping children, adults, and families rise above adversity by the belief that each of us can thrive when life has hope and opportunity.', NULL, 'JCP@RisingGround.org', '91-14 Merrick Blvd, Jamaica, NY 11432', 'https://risingground.org', ARRAY['recreational'], 'resource', NULL),
  ('Thomas White Junior Foundation', 'A charitable organization that provides community outreach about various social issues.', '(347) 948-6835', NULL, '162-04 Tuskegee Airmen Way, Jamaica, NY 11433', 'https://thomaswhitejr.org', ARRAY['recreational'], 'resource', NULL),
  ('King of Kings Foundation', 'Empower at-risk children, youth, and young adults by addressing the challenges that hinder their social growth.', NULL, 'info@kokfoundation.org', NULL, 'https://kingofkingsfoundation.org', ARRAY['recreational'], 'resource', NULL),
  ('Life Camp', 'Provide Youth + Families, impacted by violence, tools to launch sustainable careers, avert incarceration, & optimize talent so that historically marginalized communities can make a social impact that improves life for our fellow global citizens.', '(646) 258-0936', NULL, '111-12 Sutphin Boulevard, Jamaica, NY 11435', 'https://www.peaceisalifestyle.com/', ARRAY['recreational'], 'resource', NULL),
  ('100 Suits', 'Group based in Queens, New York, dedicated to empowering individuals through professional development.', '(646) 618-9797', NULL, '227-12A Merrick Boulevard, Laurelton, NY 11413', 'https://www.100suitsnyc.org/', ARRAY['recreational'], 'resource', NULL),
  ('NY Softball Cricket League', 'Group based in Queens, New York, dedicated to the development and growth of Cricket in the USA.', '(516) 650-8037', NULL, '115-56 122 Street, Ozone Park, NY 11420', NULL, ARRAY['sports'], 'resource', NULL);